# Generated by Django 2.2.4 on 2019-08-31 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bpaint_app', '0002_auto_20190830_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('medium', models.CharField(max_length=15)),
                ('number', models.IntegerField()),
                ('image_url', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('medium', models.CharField(max_length=15)),
                ('number', models.IntegerField()),
                ('image_url', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bpaint_app.Color')),
            ],
        ),
        migrations.DeleteModel(
            name='OilAcrylicColor',
        ),
        migrations.DeleteModel(
            name='WatercolorColor',
        ),
    ]
