# Generated by Django 2.2.4 on 2019-08-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpaint_app', '0003_auto_20190830_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('medium', models.CharField(max_length=15)),
                ('number', models.IntegerField()),
                ('image_filename', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='image_url',
            new_name='image_filename',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
